#pragma once

// Compatibility umbrella for the decomposed v26.0.1 public interface.
// New code should include the narrowest model/API header it needs.

#include "archive_common.h"
#include "hidden_truth_model.h"
#include "public_archive_model.h"
#include "candidate_model.h"
#include "archive_engine_state.h"
#include "evidence_potential_model.h"
#include "evidence_potential_api.h"
#include "knowledge_horizon_model.h"
#include "knowledge_horizon_api.h"
#include "contradiction_budget_model.h"
#include "contradiction_budget_api.h"
#include "candidate_artifact_plan_model.h"
#include "candidate_artifact_plan_api.h"
#include "candidate_artifact_plan_evaluation_model.h"
#include "candidate_artifact_plan_evaluation_api.h"
#include "candidate_artifact_proposal_model.h"
#include "candidate_artifact_proposal_api.h"
#include "candidate_artifact_proposal_audit_model.h"
#include "candidate_artifact_proposal_audit_api.h"
#include "candidate_artifact_draft_model.h"
#include "candidate_artifact_draft_api.h"
#include "candidate_artifact_draft_review_model.h"
#include "candidate_artifact_draft_review_api.h"
#include "control_layer_audit_model.h"
#include "control_layer_audit_api.h"
#include "validation_api.h"
#include "candidate_generation_api.h"
#include "hidden_workflows_api.h"
#include "materialization_api.h"
#include "archive_views_api.h"
#include "cli_model.h"
#include "civilization_fragment_model.h"
#include "civilization_fragments_api.h"
#include "civilization_spec_model.h"
#include "civilization_specs_api.h"
#include "civilization_bootstrap_api.h"
#include "archive_snapshot_model.h"
#include "archive_snapshot_api.h"
#include "golden_fixture_model.h"
#include "golden_fixtures_api.h"
